# -*- coding: utf-8 -*-
"""Placement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WpcJ2AgaAWUi8Z4ISWgorP9FQSscPKm
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/placement.csv')
df.head()

df.shape

df = df.iloc[:,1:]

df.head()

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

x_train

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train,y_train)

pred = clf.predict(x_test)

pred

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)